var scraper = require('./scraper');
var _       = require('underscore');
var fs      = require('fs');

scraper.scrapeTables().done(function(tables) {

    var files = {};

    tables.forEach(function(table) {

        var className = table.tableName;
        var code = '';

        code += 'var Table = require(\'../Table\');\n\n';
        code += 'module.exports = ' + className + ' = require(\'typedef\')\n\n';

        code += '// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.\n';
        code += '// For more information, see http://github.com/bvalosek/infusionsoft-api\n';
        code += '\n.class(\'' + className + '\') .extends(Table) .define({\n';

        table.fields.forEach(function(field, index) {
            if (index)
                code += ',\n';

            code += '\n';

            var meth = '__field__' + field + ': undefined';

            code += '    ' + meth;
        });

        code += '\n\n});';
        files[className + '.js'] = code;
    });

    _(files).each(function(code, filename) {
        fs.writeFile(__dirname + '/../infusionsoft/tables/' + filename, code, function(err) {
            if (err)
                console.log(err);
            else
                console.log(filename + ' updated');
        });
    });

});
