var fs = require('fs');
var Q  = require('q');

var code = '';

code += 'module.exports = InfusionsoftApi = \n\n';
code += '// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.\n';
code += '// For more information, see http://github.com/bvalosek/infusionsoft-api\n\n';
code += '{\n';

// iterate over all the files and require them into the api module
var count = 0;
var doIt = function(dir) {
    code += '    ' + dir + ': {\n';
    fs.readdirSync(__dirname + '/../infusionsoft/' + dir).forEach(function(path, n) {
        if (n)
            code += ',\n';

        var key = path.replace('.js', '');
        code += '        ' + key + ': require(\'./' + dir + '/' + path + '\')';

    });
    code += '\n    },';
    code += '\n';
};

doIt('services');
doIt('tables');

code += '};';

fs.writeFile(__dirname + '/../infusionsoft/api.js', code, function(err) {
    if (err)
        console.log(err);
    else
        console.log('Infusionsoft API interfaces and classes generated');
});
