module.exports = api =

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:03 GMT-0500 (CDT)

{

    services:
    {
        IAffiliateProgramService: require('./services/IAffiliateProgramService'),
        IAffiliateService: require('./services/IAffiliateService'),
        IContactService: require('./services/IContactService'),
        IDataService: require('./services/IDataService'),
        IDiscountService: require('./services/IDiscountService'),
        IEmailService: require('./services/IEmailService'),
        IFileService: require('./services/IFileService'),
        IFunnelService: require('./services/IFunnelService'),
        IInvoiceService: require('./services/IInvoiceService'),
        IOrderService: require('./services/IOrderService'),
        IProductService: require('./services/IProductService'),
        ISearchService: require('./services/ISearchService'),
        IShippingService: require('./services/IShippingService'),
        IWebFormService: require('./services/IWebFormService')
    },

    tables:
    {
        ActionSequence: require('./tables/ActionSequence'),
        AffResource: require('./tables/AffResource'),
        Affiliate: require('./tables/Affiliate'),
        CCharge: require('./tables/CCharge'),
        CProgram: require('./tables/CProgram'),
        Campaign: require('./tables/Campaign'),
        CampaignStep: require('./tables/CampaignStep'),
        Campaignee: require('./tables/Campaignee'),
        Company: require('./tables/Company'),
        Contact: require('./tables/Contact'),
        ContactAction: require('./tables/ContactAction'),
        ContactGroup: require('./tables/ContactGroup'),
        ContactGroupAssign: require('./tables/ContactGroupAssign'),
        ContactGroupCategory: require('./tables/ContactGroupCategory'),
        CreditCard: require('./tables/CreditCard'),
        DataFormField: require('./tables/DataFormField'),
        DataFormGroup: require('./tables/DataFormGroup'),
        DataFormTab: require('./tables/DataFormTab'),
        Expense: require('./tables/Expense'),
        FileBox: require('./tables/FileBox'),
        GroupAssign: require('./tables/GroupAssign'),
        Invoice: require('./tables/Invoice'),
        InvoiceItem: require('./tables/InvoiceItem'),
        InvoicePayment: require('./tables/InvoicePayment'),
        Job: require('./tables/Job'),
        JobRecurringInstance: require('./tables/JobRecurringInstance'),
        Lead: require('./tables/Lead'),
        LeadSource: require('./tables/LeadSource'),
        LeadSourceCategory: require('./tables/LeadSourceCategory'),
        LeadSourceExpense: require('./tables/LeadSourceExpense'),
        LeadSourceRecurringExpense: require('./tables/LeadSourceRecurringExpense'),
        MtgLead: require('./tables/MtgLead'),
        OrderItem: require('./tables/OrderItem'),
        PayPlan: require('./tables/PayPlan'),
        PayPlanItem: require('./tables/PayPlanItem'),
        Payment: require('./tables/Payment'),
        Product: require('./tables/Product'),
        ProductCategory: require('./tables/ProductCategory'),
        ProductCategoryAssign: require('./tables/ProductCategoryAssign'),
        ProductInterest: require('./tables/ProductInterest'),
        ProductInterestBundle: require('./tables/ProductInterestBundle'),
        ProductOptValue: require('./tables/ProductOptValue'),
        ProductOption: require('./tables/ProductOption'),
        RecurringOrder: require('./tables/RecurringOrder'),
        RecurringOrderWithContact: require('./tables/RecurringOrderWithContact'),
        Referral: require('./tables/Referral'),
        SavedFilter: require('./tables/SavedFilter'),
        Stage: require('./tables/Stage'),
        StageMove: require('./tables/StageMove'),
        Status: require('./tables/Status'),
        SubscriptionPlan: require('./tables/SubscriptionPlan'),
        Template: require('./tables/Template'),
        Ticket: require('./tables/Ticket'),
        TicketStage: require('./tables/TicketStage'),
        TicketType: require('./tables/TicketType'),
        User: require('./tables/User'),
        UserGroup: require('./tables/UserGroup')
    }

}