module.exports = IDiscountService = require('typedef')

// DiscountService is used to manage products. You can add, update and find
// products in addition to managing follow up sequences, tags and action sets.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IDiscountService') .define({

    // Adds a Free trial
    __xmlrpc__addFreeTrial: function(name, description, freeTrialDays,
        hidePrice, subscriptionPlanId) {},

    // Returns the options and values of the free trial id passed
    __xmlrpc__getFreeTrial: function(trialId) {},

    // Adds a order total discount
    __xmlrpc__addOrderTotalDiscount: function(name, description,
        applyDiscountToCommission, percentOrAmt, amt, payType) {},

    // Adds a order total discount
    __xmlrpc__getOrderTotalDiscount: function(id) {},

    // Adds a category discount
    __xmlrpc__addCategoryDiscount: function(name, description,
        applyDiscountToCommission, amt) {},

    // Returns the options and values of the category discount id passed
    __xmlrpc__getCategoryDiscount: function(id) {},

    // Assigns a product to a category discount
    __xmlrpc__addCategoryAssignmentToCategoryDiscount: function(id,
        productId) {},

    // Returns the options and values of the category assignment for category
    // discount passed
    __xmlrpc__getCategoryAssignmentsForCategoryDiscount: function(id) {},

    // Add a product total discount
    __xmlrpc__addProductTotalDiscount: function(name, description,
        applyDiscountToCommission, productId, percentOrAmt, amt) {},

    // Returns the options and values of the product total discount id passed
    __xmlrpc__getProductTotalDiscount: function(id) {},

    // Adds a shipping total discount
    __xmlrpc__addShippingTotalDiscount: function(name, description,
        applyDiscountToCommission, percentOrAmt, amt) {},

    // Returns the options and values of the shipping total discount id passed
    __xmlrpc__getShippingTotalDiscount: function(id) {}

});