module.exports = IFileService = require('typedef')

// The FileService methods allow you to create and modify files inside the
// Infusionsoft System.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IFileService') .define({

    // This method retrieves the file data for the given ID number.
    __xmlrpc__getFile: function(FileId) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__getDownloadUrl: function(FileId) {},

    // This method uploads the file to Infusionsoft. The optional contactId
    // parameter is used to place the file in a specific contact's filebox.
    __xmlrpc__uploadFile: function(FileName, Base64EncodedData, _ContactId) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__replaceFile: function(FileId, Base64EncodedData) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__renameFile: function(FileId, fileName) {}

});