module.exports = IOrderService = require('typedef')

// OrderService is used to build, create and charge for an order.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IOrderService') .define({

    // Returns the result of order placement. The ids of the order and invoice
    // that were created are returned along with the status of a credit card
    // charge if one was made.
    __xmlrpc__placeOrder: function(contactId, creditCardId, payPlanId,
        productIds, subscriptionPlanIds, processSpecials, promoCodes,
        _leadAffiliatedId, _affiliatedId) {}

});