module.exports = IProductService = require('typedef')

// ProductService is used to manage products. You can add, update and find
// products in addition to managing follow up sequences, tags and action sets.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IProductService') .define({

    // Returns a product inventory provided the Id
    __xmlrpc__getInventory: function(productId) {},

    // Increments the inventory by one product, provided you pass the
    // productId to increment withy
    __xmlrpc__incrementInventory: function(productId) {},

    // Decrements the inventory by one product, provided you pass the
    // productId to decrement with
    __xmlrpc__decrementInventory: function(productId) {},

    // Increases the inventory with a particular product by the quantity you
    // specify
    __xmlrpc__increaseInventory: function(productId, quantity) {},

    // Decreases the inventory with a particular product by the quantity you
    // specify
    __xmlrpc__decreaseInventory: function(productId, quantity) {},

    // Deactivates the specified Credit Card
    __xmlrpc__deactivateCreditCard: function(creditCardId) {}

});