module.exports = ActionSequence = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('ActionSequence') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__string__read__TemplateName:
        'TemplateName',

    __static__field__string__read__VisibleToTheseUsers:
        'VisibleToTheseUsers'

});