var Table = require('../Table');

module.exports = Affiliate = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Affiliate') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__ParentId: undefined,

    __field__LeadAmt: undefined,

    __field__LeadPercent: undefined,

    __field__SaleAmt: undefined,

    __field__SalePercent: undefined,

    __field__PayoutType: undefined,

    __field__DefCommissionType: undefined,

    __field__Status: undefined,

    __field__AffName: undefined,

    __field__Password: undefined,

    __field__AffCode: undefined,

    __field__NotifyLead: undefined,

    __field__NotifySale: undefined,

    __field__LeadCookieFor: undefined

});