module.exports = Affiliate = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data related to the Affiliate records within Infusionsoft.
.class('Affiliate') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__ContactId:
        'ContactId',

    __static__field__number__edit__delete__add__read__ParentId:
        'ParentId',

    __static__field__number__edit__delete__add__read__LeadAmt:
        'LeadAmt',

    __static__field__number__edit__delete__add__read__LeadPercent:
        'LeadPercent',

    __static__field__number__edit__delete__add__read__SaleAmt:
        'SaleAmt',

    __static__field__number__edit__delete__add__read__SalePercent:
        'SalePercent',

    __static__field__number__edit__delete__add__read__PayoutType:
        'PayoutType',

    __static__field__number__edit__delete__add__read__DefCommissionType:
        'DefCommissionType',

    __static__field__number__edit__delete__add__read__Status:
        'Status',

    __static__field__string__edit__delete__add__read__AffName:
        'AffName',

    __static__field__string__edit__delete__add__read__Password:
        'Password',

    __static__field__string__edit__delete__add__read__AffCode:
        'AffCode',

    __static__field__number__edit__delete__add__read__NotifyLead:
        'NotifyLead',

    __static__field__number__edit__delete__add__read__NotifySale:
        'NotifySale',

    __static__field__number__edit__delete__add__read__LeadCookieFor:
        'LeadCookieFor'

});