var Table = require('../Table');

module.exports = AffResource = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('AffResource') .extends(Table) .define({

    __field__Id: undefined,

    __field__Title: undefined,

    __field__ResourceType: undefined,

    __field__ResourceOrder: undefined,

    __field__ResourceHTML: undefined,

    __field__ResourceHREF: undefined,

    __field__Notes: undefined,

    __field__ProgramIds: undefined

});