module.exports = AffResource = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

.class('AffResource') .define({

    __static__field__primary__number__edit__delete__add__read__Id:
        'Id',

    __static__field__string__edit__delete__add__read__Title:
        'Title',

    __static__field__string__edit__delete__add__read__ResourceType:
        'ResourceType',

    __static__field__string__edit__delete__add__read__ResourceOrder:
        'ResourceOrder',

    __static__field__string__edit__delete__add__read__ResourceHTML:
        'ResourceHTML',

    __static__field__string__edit__delete__add__read__ResourceHREF:
        'ResourceHREF',

    __static__field__string__edit__delete__add__read__Notes:
        'Notes',

    __static__field__string__edit__delete__add__read__ProgramIds:
        'ProgramIds'

});