module.exports = Campaignee = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('Campaignee') .define({

    __static__field__number__read__CampaignId:
        'CampaignId',

    __static__field__enum__read__Status:
        'Status',

    __static__field__string__read__Campaign:
        'Campaign',

    __static__field__number__read__ContactId:
        'ContactId'

});