var Table = require('../Table');

module.exports = Campaignee = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Campaignee') .extends(Table) .define({

    __field__CampaignId: undefined,

    __field__Status: undefined,

    __field__Campaign: undefined,

    __field__ContactId: undefined

});