module.exports = Campaignee = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table has one entry for each person in a single follow-up sequence. One
// contact in three different follow-up sequences means you will find three
// entries in this table for that contact record.
.class('Campaignee') .define({

    __static__field__number__read__CampaignId:
        'CampaignId',

    __static__field__enum__read__Status:
        'Status',

    __static__field__string__read__Campaign:
        'Campaign',

    __static__field__number__read__ContactId:
        'ContactId'

});