module.exports = CCharge = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data related to credit card charges processed from
// Infusionsoft through a merchant account.
.class('CCharge') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__CCId:
        'CCId',

    __static__field__string__read__PaymentId:
        'PaymentId',

    __static__field__string__read__MerchantId:
        'MerchantId',

    __static__field__string__read__OrderNum:
        'OrderNum',

    __static__field__string__read__RefNum:
        'RefNum',

    __static__field__string__read__ApprCode:
        'ApprCode',

    __static__field__number__read__Amt:
        'Amt'

});