module.exports = CCharge = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('CCharge') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__number__read__CCId:
        'CCId',

    __static__field__string__read__PaymentId:
        'PaymentId',

    __static__field__string__read__MerchantId:
        'MerchantId',

    __static__field__string__read__OrderNum:
        'OrderNum',

    __static__field__string__read__RefNum:
        'RefNum',

    __static__field__string__read__ApprCode:
        'ApprCode',

    __static__field__number__read__Amt:
        'Amt'

});