var Table = require('../Table');

module.exports = CCharge = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('CCharge') .extends(Table) .define({

    __field__Id: undefined,

    __field__CCId: undefined,

    __field__PaymentId: undefined,

    __field__MerchantId: undefined,

    __field__OrderNum: undefined,

    __field__RefNum: undefined,

    __field__ApprCode: undefined,

    __field__Amt: undefined

});