var Table = require('../Table');

module.exports = ContactGroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ContactGroupAssign') .extends(Table) .define({

    __field__GroupId: undefined,

    __field__ContactGroup: undefined,

    __field__DateCreated: undefined,

    __field__ContactId: undefined

});