module.exports = ContactGroupCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table holds tag categories. For each category you have in your system,
// there will be one row in this table.
.class('ContactGroupCategory') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__CategoryName:
        'CategoryName',

    __static__field__string__edit__add__read__CategoryDescription:
        'CategoryDescription'

});