module.exports = ContactGroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table has one entry for each tag a single contact has. If you have one
// contact with five tags, you will find five entries in this table for that given
// contact
.class('ContactGroupAssign') .define({

    __static__field__number__read__GroupId:
        'GroupId',

    __static__field__string__read__ContactGroup:
        'ContactGroup',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__read__ContactId:
        'ContactId'

});