module.exports = ContactAction = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data for tasks, notes, and appointments within Infusionsoft.
.class('ContactAction') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__ContactId:
        'ContactId',

    __static__field__number__edit__delete__add__read__OpportunityId:
        'OpportunityId',

    __static__field__string__edit__delete__add__read__ActionType:
        'ActionType',

    __static__field__string__edit__delete__add__read__ActionDescription:
        'ActionDescription',

    __static__field__datetime__edit__delete__add__read__CreationDate:
        'CreationDate',

    __static__field__string__edit__delete__add__read__CreationNotes:
        'CreationNotes',

    __static__field__datetime__edit__delete__add__read__CompletionDate:
        'CompletionDate',

    __static__field__datetime__edit__delete__add__read__ActionDate:
        'ActionDate',

    __static__field__datetime__edit__delete__add__read__EndDate:
        'EndDate',

    __static__field__datetime__edit__delete__add__read__PopupDate:
        'PopupDate',

    __static__field__number__edit__delete__add__read__UserID:
        'UserID',

    __static__field__number__edit__delete__add__read__Accepted:
        'Accepted',

    __static__field__number__edit__delete__add__read__CreatedBy:
        'CreatedBy',

    __static__field__datetime__read__LastUpdated:
        'LastUpdated',

    __static__field__number__read__LastUpdatedBy:
        'LastUpdatedBy',

    __static__field__number__edit__delete__add__read__Priority:
        'Priority',

    __static__field__number__edit__delete__add__read__IsAppointment:
        'IsAppointment'

});