module.exports = ContactGroup = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data for the tags you have created within Infusionsoft. In the
// Infusionsoft "ice age" tags were referred to as "groups", thus the table name.
.class('ContactGroup') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__GroupName:
        'GroupName',

    __static__field__number__edit__add__read__GroupCategoryId:
        'GroupCategoryId',

    __static__field__string__edit__add__read__GroupDescription:
        'GroupDescription'

});