var Table = require('../Table');

module.exports = Contact = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Contact') .extends(Table) .define({

    __field__Address1Type: undefined,

    __field__Address2Street1: undefined,

    __field__Address2Street2: undefined,

    __field__Address2Type: undefined,

    __field__Address3Street1: undefined,

    __field__Address3Street2: undefined,

    __field__Address3Type: undefined,

    __field__Anniversary: undefined,

    __field__AssistantName: undefined,

    __field__AssistantPhone: undefined,

    __field__BillingInformation: undefined,

    __field__Birthday: undefined,

    __field__City: undefined,

    __field__City2: undefined,

    __field__City3: undefined,

    __field__Company: undefined,

    __field__AccountId: undefined,

    __field__CompanyID: undefined,

    __field__ContactNotes: undefined,

    __field__ContactType: undefined,

    __field__Country: undefined,

    __field__Country2: undefined,

    __field__Country3: undefined,

    __field__CreatedBy: undefined,

    __field__DateCreated: undefined,

    __field__Email: undefined,

    __field__EmailAddress2: undefined,

    __field__EmailAddress3: undefined,

    __field__Fax1: undefined,

    __field__Fax1Type: undefined,

    __field__Fax2: undefined,

    __field__Fax2Type: undefined,

    __field__FirstName: undefined,

    __field__Groups: undefined,

    __field__Id: undefined,

    __field__JobTitle: undefined,

    __field__LastName: undefined,

    __field__LastUpdated: undefined,

    __field__LastUpdatedBy: undefined,

    __field__Leadsource: undefined,

    __field__LeadSourceId: undefined,

    __field__MiddleName: undefined,

    __field__Nickname: undefined,

    __field__OwnerID: undefined,

    __field__Password: undefined,

    __field__Phone1: undefined,

    __field__Phone1Ext: undefined,

    __field__Phone1Type: undefined,

    __field__Phone2: undefined,

    __field__Phone2Ext: undefined,

    __field__Phone2Type: undefined,

    __field__Phone3: undefined,

    __field__Phone3Ext: undefined,

    __field__Phone3Type: undefined,

    __field__Phone4: undefined,

    __field__Phone4Ext: undefined,

    __field__Phone4Type: undefined,

    __field__Phone5: undefined,

    __field__Phone5Ext: undefined,

    __field__Phone5Type: undefined,

    __field__PostalCode: undefined,

    __field__PostalCode2: undefined,

    __field__PostalCode3: undefined,

    __field__ReferralCode: undefined,

    __field__SpouseName: undefined,

    __field__State: undefined,

    __field__State2: undefined,

    __field__State3: undefined,

    __field__StreetAddress1: undefined,

    __field__StreetAddress2: undefined,

    __field__Suffix: undefined,

    __field__Title: undefined,

    __field__Username: undefined,

    __field__Validated: undefined,

    __field__Website: undefined,

    __field__ZipFour1: undefined,

    __field__ZipFour2: undefined,

    __field__ZipFour3: undefined

});