var Table = require('../Table');

module.exports = ContactAction = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ContactAction') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__OpportunityId: undefined,

    __field__ActionType: undefined,

    __field__ActionDescription: undefined,

    __field__CreationDate: undefined,

    __field__CreationNotes: undefined,

    __field__CompletionDate: undefined,

    __field__ActionDate: undefined,

    __field__EndDate: undefined,

    __field__PopupDate: undefined,

    __field__UserID: undefined,

    __field__Accepted: undefined,

    __field__CreatedBy: undefined,

    __field__LastUpdated: undefined,

    __field__LastUpdatedBy: undefined,

    __field__Priority: undefined,

    __field__IsAppointment: undefined

});