var Table = require('../Table');

module.exports = ContactGroupCategory = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ContactGroupCategory') .extends(Table) .define({

    __field__Id: undefined,

    __field__CategoryName: undefined,

    __field__CategoryDescription: undefined

});