module.exports = ContactGroup = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('ContactGroup') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__GroupName:
        'GroupName',

    __static__field__number__edit__add__read__GroupCategoryId:
        'GroupCategoryId',

    __static__field__string__edit__add__read__GroupDescription:
        'GroupDescription'

});