module.exports = ContactGroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('ContactGroupAssign') .define({

    __static__field__number__read__GroupId:
        'GroupId',

    __static__field__string__read__ContactGroup:
        'ContactGroup',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__read__ContactId:
        'ContactId'

});