var Table = require('../Table');

module.exports = CProgram = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('CProgram') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProgramName: undefined,

    __field__DefaultPrice: undefined,

    __field__DefaultCycle: undefined,

    __field__DefaultFrequency: undefined,

    __field__Sku: undefined,

    __field__ShortDescription: undefined,

    __field__BillingType: undefined,

    __field__Description: undefined,

    __field__HideInStore: undefined,

    __field__Status: undefined,

    __field__Active: undefined,

    __field__LargeImage: undefined,

    __field__Taxable: undefined,

    __field__Family: undefined,

    __field__ProductId: undefined

});