module.exports = CProgram = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data about all the subscription programs you have created
// within Infusionsoft.
.class('CProgram') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__ProgramName:
        'ProgramName',

    __static__field__number__edit__add__read__DefaultPrice:
        'DefaultPrice',

    __static__field__string__edit__add__read__DefaultCycle:
        'DefaultCycle',

    __static__field__number__edit__add__read__DefaultFrequency:
        'DefaultFrequency',

    __static__field__string__edit__add__read__Sku:
        'Sku',

    __static__field__string__edit__add__read__ShortDescription:
        'ShortDescription',

    __static__field__string__edit__add__read__BillingType:
        'BillingType',

    __static__field__string__edit__add__read__Description:
        'Description',

    __static__field__number__edit__add__read__HideInStore:
        'HideInStore',

    __static__field__number__edit__add__read__Status:
        'Status',

    __static__field__boolean__edit__add__read__Active:
        'Active',

    __static__field__blob__edit__add__read__LargeImage:
        'LargeImage',

    __static__field__number__edit__add__read__Taxable:
        'Taxable',

    __static__field__string__edit__add__read__Family:
        'Family',

    __static__field__number__edit__add__read__ProductId:
        'ProductId'

});