var Table = require('../Table');

module.exports = CreditCard = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('CreditCard') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__BillName: undefined,

    __field__FirstName: undefined,

    __field__LastName: undefined,

    __field__PhoneNumber: undefined,

    __field__Email: undefined,

    __field__BillAddress1: undefined,

    __field__BillAddress2: undefined,

    __field__BillCity: undefined,

    __field__BillState: undefined,

    __field__BillZip: undefined,

    __field__BillCountry: undefined,

    __field__ShipFirstName: undefined,

    __field__ShipMiddleName: undefined,

    __field__ShipLastName: undefined,

    __field__ShipCompanyName: undefined,

    __field__ShipPhoneNumber: undefined,

    __field__ShipAddress1: undefined,

    __field__ShipAddress2: undefined,

    __field__ShipCity: undefined,

    __field__ShipState: undefined,

    __field__ShipZip: undefined,

    __field__ShipCountry: undefined,

    __field__ShipName: undefined,

    __field__NameOnCard: undefined,

    __field__CardNumber: undefined,

    __field__Last4: undefined,

    __field__ExpirationMonth: undefined,

    __field__ExpirationYear: undefined,

    __field__CVV2: undefined,

    __field__Status: undefined,

    __field__CardType: undefined,

    __field__StartDateMonth: undefined,

    __field__StartDateYear: undefined,

    __field__MaestroIssueNumber: undefined

});