module.exports = CreditCard = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds all data tied to credit cards. For each credit card in the
// system there will be one row in this table.
.class('CreditCard') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__add__read__ContactId:
        'ContactId',

    __static__field__string__edit__add__read__BillName:
        'BillName',

    __static__field__string__edit__add__read__FirstName:
        'FirstName',

    __static__field__string__edit__add__read__LastName:
        'LastName',

    __static__field__string__edit__add__read__PhoneNumber:
        'PhoneNumber',

    __static__field__string__edit__add__read__Email:
        'Email',

    __static__field__string__edit__add__read__BillAddress1:
        'BillAddress1',

    __static__field__string__edit__add__read__BillAddress2:
        'BillAddress2',

    __static__field__string__edit__add__read__BillCity:
        'BillCity',

    __static__field__string__edit__add__read__BillState:
        'BillState',

    __static__field__string__edit__add__read__BillZip:
        'BillZip',

    __static__field__string__edit__add__read__BillCountry:
        'BillCountry',

    __static__field__string__edit__add__read__ShipFirstName:
        'ShipFirstName',

    __static__field__string__edit__add__read__ShipMiddleName:
        'ShipMiddleName',

    __static__field__string__edit__add__read__ShipLastName:
        'ShipLastName',

    __static__field__string__edit__add__read__ShipCompanyName:
        'ShipCompanyName',

    __static__field__string__edit__add__read__ShipPhoneNumber:
        'ShipPhoneNumber',

    __static__field__string__edit__add__read__ShipAddress1:
        'ShipAddress1',

    __static__field__string__edit__add__read__ShipAddress2:
        'ShipAddress2',

    __static__field__string__edit__add__read__ShipCity:
        'ShipCity',

    __static__field__string__edit__add__read__ShipState:
        'ShipState',

    __static__field__string__edit__add__read__ShipZip:
        'ShipZip',

    __static__field__string__edit__add__read__ShipCountry:
        'ShipCountry',

    __static__field__string__edit__add__read__ShipName:
        'ShipName',

    __static__field__string__edit__add__read__NameOnCard:
        'NameOnCard',

    __static__field__string__add__CardNumber:
        'CardNumber',

    __static__field__string__read__Last4:
        'Last4',

    __static__field__string__edit__add__read__ExpirationMonth:
        'ExpirationMonth',

    __static__field__string__edit__add__read__ExpirationYear:
        'ExpirationYear',

    __static__field__string__edit__add__CVV2:
        'CVV2',

    __static__field__number__read__Status:
        'Status',

    __static__field__string__edit__add__read__CardType:
        'CardType',

    __static__field__string__edit__add__read__StartDateMonth:
        'StartDateMonth',

    __static__field__string__edit__add__read__StartDateYear:
        'StartDateYear',

    __static__field__string__edit__add__read__MaestroIssueNumber:
        'MaestroIssueNumber'

});