module.exports = DataFormTab = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds your custom field tabs. These tabs are where your custom
// fields sit on contact records, orders, opportunities, etc.
.class('DataFormTab') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__FormId:
        'FormId',

    __static__field__string__read__TabName:
        'TabName'

});