module.exports = DataFormField = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table holds custom fields. For each field there will be one row in this
// table.
.class('DataFormField') .define({

    __static__field__number__read__DataType:
        'DataType',

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__FormId:
        'FormId',

    __static__field__number__edit__read__GroupId:
        'GroupId',

    __static__field__string__edit__read__Name:
        'Name',

    __static__field__string__edit__read__Label:
        'Label',

    __static__field__string__edit__read__DefaultValue:
        'DefaultValue',

    __static__field__string__edit__read__Values:
        'Values',

    __static__field__number__edit__read__ListRows:
        'ListRows'

});