module.exports = DataFormGroup = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds the headers that custom fields are displayed under.
.class('DataFormGroup') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__TabId:
        'TabId',

    __static__field__string__read__Name:
        'Name'

});