var Table = require('../Table');

module.exports = Expense = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Expense') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__ExpenseType: undefined,

    __field__TypeId: undefined,

    __field__ExpenseAmt: undefined,

    __field__DateIncurred: undefined

});