module.exports = Expense = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// These are the expenses incurred by opportunities and leadsources.
.class('Expense') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__ContactId:
        'ContactId',

    __static__field__enum__read__ExpenseType:
        'ExpenseType',

    __static__field__number__read__TypeId:
        'TypeId',

    __static__field__number__read__ExpenseAmt:
        'ExpenseAmt',

    __static__field__datetime__read__DateIncurred:
        'DateIncurred'

});