var Table = require('../Table');

module.exports = FileBox = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('FileBox') .extends(Table) .define({

    __field__Id: undefined,

    __field__FileName: undefined,

    __field__Extension: undefined,

    __field__FileSize: undefined,

    __field__ContactId: undefined,

    __field__Public: undefined

});