module.exports = FileBox = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('FileBox') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__string__read__FileName:
        'FileName',

    __static__field__string__read__Extension:
        'Extension',

    __static__field__number__read__FileSize:
        'FileSize',

    __static__field__number__read__ContactId:
        'ContactId',

    __static__field__number__read__Public:
        'Public'

});