module.exports = GroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table holds the data related to what user groups your system users are a
// part of.
.class('GroupAssign') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__UserId:
        'UserId',

    __static__field__number__read__GroupId:
        'GroupId',

    __static__field__number__read__Admin:
        'Admin'

});