var Table = require('../Table');

module.exports = GroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('GroupAssign') .extends(Table) .define({

    __field__Id: undefined,

    __field__UserId: undefined,

    __field__GroupId: undefined,

    __field__Admin: undefined

});