var Table = require('../Table');

module.exports = InvoiceItem = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('InvoiceItem') .extends(Table) .define({

    __field__Id: undefined,

    __field__InvoiceId: undefined,

    __field__OrderItemId: undefined,

    __field__InvoiceAmt: undefined,

    __field__Discount: undefined,

    __field__DateCreated: undefined,

    __field__Description: undefined,

    __field__CommissionStatus: undefined

});