module.exports = InvoiceItem = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('InvoiceItem') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__InvoiceId:
        'InvoiceId',

    __static__field__number__read__OrderItemId:
        'OrderItemId',

    __static__field__number__edit__add__read__InvoiceAmt:
        'InvoiceAmt',

    __static__field__number__edit__add__read__Discount:
        'Discount',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__string__edit__add__read__Description:
        'Description',

    __static__field__number__edit__add__read__CommissionStatus:
        'CommissionStatus'

});