var Table = require('../Table');

module.exports = Invoice = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Invoice') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__JobId: undefined,

    __field__DateCreated: undefined,

    __field__InvoiceTotal: undefined,

    __field__TotalPaid: undefined,

    __field__TotalDue: undefined,

    __field__PayStatus: undefined,

    __field__CreditStatus: undefined,

    __field__RefundStatus: undefined,

    __field__PayPlanStatus: undefined,

    __field__AffiliateId: undefined,

    __field__LeadAffiliateId: undefined,

    __field__PromoCode: undefined,

    __field__InvoiceType: undefined,

    __field__Description: undefined,

    __field__ProductSold: undefined,

    __field__Synced: undefined

});