module.exports = InvoiceItem = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table has one row for each "line item" found on an invoice. If there is an
// order for one product that also includes tax and shipping, you will find three
// rows on this table related to that particular InvoiceId.
.class('InvoiceItem') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__InvoiceId:
        'InvoiceId',

    __static__field__number__read__OrderItemId:
        'OrderItemId',

    __static__field__number__edit__add__read__InvoiceAmt:
        'InvoiceAmt',

    __static__field__number__edit__add__read__Discount:
        'Discount',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__string__edit__add__read__Description:
        'Description',

    __static__field__number__edit__add__read__CommissionStatus:
        'CommissionStatus'

});