var Table = require('../Table');

module.exports = Job = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Job') .extends(Table) .define({

    __field__Id: undefined,

    __field__JobTitle: undefined,

    __field__ContactId: undefined,

    __field__StartDate: undefined,

    __field__DueDate: undefined,

    __field__JobNotes: undefined,

    __field__ProductId: undefined,

    __field__JobStatus: undefined,

    __field__DateCreated: undefined,

    __field__JobRecurringId: undefined,

    __field__OrderType: undefined,

    __field__OrderStatus: undefined,

    __field__ShipFirstName: undefined,

    __field__ShipMiddleName: undefined,

    __field__ShipLastName: undefined,

    __field__ShipCompany: undefined,

    __field__ShipPhone: undefined,

    __field__ShipStreet1: undefined,

    __field__ShipStreet2: undefined,

    __field__ShipCity: undefined,

    __field__ShipState: undefined,

    __field__ShipZip: undefined,

    __field__ShipCountry: undefined

});