module.exports = Job = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds one-time order data (not subscriptions).
.class('Job') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__JobTitle:
        'JobTitle',

    __static__field__number__edit__add__read__ContactId:
        'ContactId',

    __static__field__datetime__edit__add__read__StartDate:
        'StartDate',

    __static__field__datetime__edit__add__read__DueDate:
        'DueDate',

    __static__field__string__edit__add__read__JobNotes:
        'JobNotes',

    __static__field__number__edit__add__read__ProductId:
        'ProductId',

    __static__field__string__edit__add__read__JobStatus:
        'JobStatus',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__read__JobRecurringId:
        'JobRecurringId',

    __static__field__string__edit__add__read__OrderType:
        'OrderType',

    __static__field__number__edit__add__read__OrderStatus:
        'OrderStatus',

    __static__field__string__edit__add__read__ShipFirstName:
        'ShipFirstName',

    __static__field__string__edit__add__read__ShipMiddleName:
        'ShipMiddleName',

    __static__field__string__edit__add__read__ShipLastName:
        'ShipLastName',

    __static__field__string__edit__add__read__ShipCompany:
        'ShipCompany',

    __static__field__string__edit__add__read__ShipPhone:
        'ShipPhone',

    __static__field__string__edit__add__read__ShipStreet1:
        'ShipStreet1',

    __static__field__string__edit__add__read__ShipStreet2:
        'ShipStreet2',

    __static__field__string__edit__add__read__ShipCity:
        'ShipCity',

    __static__field__string__edit__add__read__ShipState:
        'ShipState',

    __static__field__string__edit__add__read__ShipZip:
        'ShipZip',

    __static__field__string__edit__add__read__ShipCountry:
        'ShipCountry'

});