var Table = require('../Table');

module.exports = JobRecurringInstance = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('JobRecurringInstance') .extends(Table) .define({

    __field__Id: undefined,

    __field__RecurringId: undefined,

    __field__InvoiceItemId: undefined,

    __field__Status: undefined,

    __field__AutoCharge: undefined,

    __field__StartDate: undefined,

    __field__EndDate: undefined,

    __field__DateCreated: undefined,

    __field__Description: undefined

});