module.exports = JobRecurringInstance = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data related to one instance of a subscription. For each
// recurring of the subscription, you will find one entry in this table.
.class('JobRecurringInstance') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__RecurringId:
        'RecurringId',

    __static__field__number__edit__add__read__InvoiceItemId:
        'InvoiceItemId',

    __static__field__number__edit__add__read__Status:
        'Status',

    __static__field__number__edit__add__read__AutoCharge:
        'AutoCharge',

    __static__field__datetime__edit__add__read__StartDate:
        'StartDate',

    __static__field__datetime__edit__add__read__EndDate:
        'EndDate',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__string__edit__add__read__Description:
        'Description'

});