module.exports = LeadSource = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds data related to each of the Leadsources you have created under
// the Setup>Leadsources menu inside Infusionsoft.
.class('LeadSource') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__Name:
        'Name',

    __static__field__string__edit__add__read__Description:
        'Description',

    __static__field__datetime__edit__add__read__StartDate:
        'StartDate',

    __static__field__datetime__edit__add__read__EndDate:
        'EndDate',

    __static__field__string__edit__add__read__CostPerLead:
        'CostPerLead',

    __static__field__string__edit__add__read__Vendor:
        'Vendor',

    __static__field__string__edit__add__read__Medium:
        'Medium',

    __static__field__string__edit__add__read__Message:
        'Message',

    __static__field__number__edit__add__read__LeadSourceCategoryId:
        'LeadSourceCategoryId',

    __static__field__string__edit__add__read__Status:
        'Status'

});