var Table = require('../Table');

module.exports = Lead = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Lead') .extends(Table) .define({

    __field__Id: undefined,

    __field__OpportunityTitle: undefined,

    __field__ContactID: undefined,

    __field__AffiliateId: undefined,

    __field__UserID: undefined,

    __field__StageID: undefined,

    __field__StatusID: undefined,

    __field__Leadsource: undefined,

    __field__Objection: undefined,

    __field__ProjectedRevenueLow: undefined,

    __field__ProjectedRevenueHigh: undefined,

    __field__OpportunityNotes: undefined,

    __field__DateCreated: undefined,

    __field__LastUpdated: undefined,

    __field__LastUpdatedBy: undefined,

    __field__CreatedBy: undefined,

    __field__EstimatedCloseDate: undefined,

    __field__NextActionDate: undefined,

    __field__NextActionNotes: undefined

});