module.exports = Lead = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds opportunity record data.
.class('Lead') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__delete__add__read__OpportunityTitle:
        'OpportunityTitle',

    __static__field__number__edit__delete__add__read__ContactID:
        'ContactID',

    __static__field__number__edit__delete__add__read__AffiliateId:
        'AffiliateId',

    __static__field__number__edit__delete__add__read__UserID:
        'UserID',

    __static__field__number__edit__delete__add__read__StageID:
        'StageID',

    __static__field__number__edit__delete__add__read__StatusID:
        'StatusID',

    __static__field__string__add__read__Leadsource:
        'Leadsource',

    __static__field__string__edit__delete__add__read__Objection:
        'Objection',

    __static__field__number__edit__delete__add__read__ProjectedRevenueLow:
        'ProjectedRevenueLow',

    __static__field__number__edit__delete__add__read__ProjectedRevenueHigh:
        'ProjectedRevenueHigh',

    __static__field__string__edit__delete__add__read__OpportunityNotes:
        'OpportunityNotes',

    __static__field__datetime__edit__delete__read__DateCreated:
        'DateCreated',

    __static__field__datetime__edit__delete__read__LastUpdated:
        'LastUpdated',

    __static__field__number__edit__delete__add__read__LastUpdatedBy:
        'LastUpdatedBy',

    __static__field__number__edit__delete__add__read__CreatedBy:
        'CreatedBy',

    __static__field__datetime__edit__delete__add__read__EstimatedCloseDate:
        'EstimatedCloseDate',

    __static__field__datetime__edit__delete__add__read__NextActionDate:
        'NextActionDate',

    __static__field__string__edit__delete__add__read__NextActionNotes:
        'NextActionNotes'

});