module.exports = LeadSourceCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

.class('LeadSourceCategory') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__Name:
        'Name',

    __static__field__string__edit__add__read__Description:
        'Description'

});