module.exports = LeadSourceExpense = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 13:46:55 GMT-0500 (CDT)

.class('LeadSourceExpense') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__LeadSourceRecurringExpenseId:
        'LeadSourceRecurringExpenseId',

    __static__field__number__edit__delete__add__read__LeadSourceId:
        'LeadSourceId',

    __static__field__string__edit__delete__add__read__Title:
        'Title',

    __static__field__string__edit__delete__add__read__Notes:
        'Notes',

    __static__field__number__edit__delete__add__read__Amount:
        'Amount',

    __static__field__datetime__edit__delete__add__read__DateIncurred:
        'DateIncurred'

});