var Table = require('../Table');

module.exports = LeadSourceExpense = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('LeadSourceExpense') .extends(Table) .define({

    __field__Id: undefined,

    __field__LeadSourceRecurringExpenseId: undefined,

    __field__LeadSourceId: undefined,

    __field__Title: undefined,

    __field__Notes: undefined,

    __field__Amount: undefined,

    __field__DateIncurred: undefined

});