var Table = require('../Table');

module.exports = LeadSource = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('LeadSource') .extends(Table) .define({

    __field__Id: undefined,

    __field__Name: undefined,

    __field__Description: undefined,

    __field__StartDate: undefined,

    __field__EndDate: undefined,

    __field__CostPerLead: undefined,

    __field__Vendor: undefined,

    __field__Medium: undefined,

    __field__Message: undefined,

    __field__LeadSourceCategoryId: undefined,

    __field__Status: undefined

});