var Table = require('../Table');

module.exports = MtgLead = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('MtgLead') .extends(Table) .define({

    __field__Id: undefined,

    __field__DateAppraisalOrdered: undefined,

    __field__DateAppraisalDone: undefined,

    __field__DateAppraisalReceived: undefined,

    __field__DateTitleOrdered: undefined,

    __field__DateTitleReceived: undefined,

    __field__DateRateLocked: undefined,

    __field__DateRateLockExpires: undefined,

    __field__CreditReportDate: undefined,

    __field__ApplicationDate: undefined,

    __field__ActualCloseDate: undefined,

    __field__FundingDate: undefined

});