module.exports = OrderItem = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds line items for one-time orders. For each product, tax,
// discount, or shipping found on an order, there will be one entry in this table
// found.
.class('OrderItem') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__OrderId:
        'OrderId',

    __static__field__number__edit__add__read__ProductId:
        'ProductId',

    __static__field__number__edit__add__read__SubscriptionPlanId:
        'SubscriptionPlanId',

    __static__field__string__edit__add__read__ItemName:
        'ItemName',

    __static__field__number__edit__add__read__Qty:
        'Qty',

    __static__field__number__edit__add__read__CPU:
        'CPU',

    __static__field__number__edit__add__read__PPU:
        'PPU',

    __static__field__string__edit__add__read__ItemDescription:
        'ItemDescription',

    __static__field__number__edit__add__read__ItemType:
        'ItemType',

    __static__field__string__edit__add__read__Notes:
        'Notes'

});