var Table = require('../Table');

module.exports = OrderItem = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('OrderItem') .extends(Table) .define({

    __field__Id: undefined,

    __field__OrderId: undefined,

    __field__ProductId: undefined,

    __field__SubscriptionPlanId: undefined,

    __field__ItemName: undefined,

    __field__Qty: undefined,

    __field__CPU: undefined,

    __field__PPU: undefined,

    __field__ItemDescription: undefined,

    __field__ItemType: undefined,

    __field__Notes: undefined

});