var Table = require('../Table');

module.exports = Payment = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Payment') .extends(Table) .define({

    __field__Id: undefined,

    __field__PayDate: undefined,

    __field__UserId: undefined,

    __field__PayAmt: undefined,

    __field__PayType: undefined,

    __field__ContactId: undefined,

    __field__PayNote: undefined,

    __field__InvoiceId: undefined,

    __field__RefundId: undefined,

    __field__ChargeId: undefined,

    __field__Commission: undefined,

    __field__Synced: undefined

});