module.exports = Payment = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('Payment') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__datetime__read__PayDate:
        'PayDate',

    __static__field__number__read__UserId:
        'UserId',

    __static__field__number__read__PayAmt:
        'PayAmt',

    __static__field__string__read__PayType:
        'PayType',

    __static__field__number__read__ContactId:
        'ContactId',

    __static__field__string__read__PayNote:
        'PayNote',

    __static__field__number__read__InvoiceId:
        'InvoiceId',

    __static__field__number__read__RefundId:
        'RefundId',

    __static__field__number__read__ChargeId:
        'ChargeId',

    __static__field__number__read__Commission:
        'Commission',

    __static__field__number__read__Synced:
        'Synced'

});