var Table = require('../Table');

module.exports = PayPlanItem = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('PayPlanItem') .extends(Table) .define({

    __field__Id: undefined,

    __field__PayPlanId: undefined,

    __field__DateDue: undefined,

    __field__AmtDue: undefined,

    __field__Status: undefined,

    __field__AmtPaid: undefined

});