var Table = require('../Table');

module.exports = PayPlan = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('PayPlan') .extends(Table) .define({

    __field__Id: undefined,

    __field__InvoiceId: undefined,

    __field__DateDue: undefined,

    __field__AmtDue: undefined,

    __field__Type: undefined,

    __field__InitDate: undefined,

    __field__StartDate: undefined,

    __field__FirstPayAmt: undefined

});