module.exports = PayPlan = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('PayPlan') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__number__read__InvoiceId:
        'InvoiceId',

    __static__field__datetime__read__DateDue:
        'DateDue',

    __static__field__number__read__AmtDue:
        'AmtDue',

    __static__field__number__read__Type:
        'Type',

    __static__field__datetime__read__InitDate:
        'InitDate',

    __static__field__datetime__read__StartDate:
        'StartDate',

    __static__field__number__read__FirstPayAmt:
        'FirstPayAmt'

});