var Table = require('../Table');

module.exports = ProductInterest = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ProductInterest') .extends(Table) .define({

    __field__Id: undefined,

    __field__ObjectId: undefined,

    __field__ObjType: undefined,

    __field__ProductId: undefined,

    __field__ProductType: undefined,

    __field__Qty: undefined,

    __field__DiscountPercent: undefined

});