var Table = require('../Table');

module.exports = ProductOption = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ProductOption') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProductId: undefined,

    __field__Label: undefined,

    __field__IsRequired: undefined,

    __field__Order: undefined,

    __field__Name: undefined,

    __field__MaxChars: undefined,

    __field__CanEndWith: undefined,

    __field__MinChars: undefined,

    __field__AllowSpaces: undefined,

    __field__TextMessage: undefined,

    __field__OptionType: undefined,

    __field__CanContain: undefined,

    __field__CanStartWith: undefined

});