module.exports = ProductCategoryAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table holds the categories that each product has been assigned to be a
// part of
.class('ProductCategoryAssign') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__ProductId:
        'ProductId',

    __static__field__number__edit__add__read__ProductCategoryId:
        'ProductCategoryId'

});