module.exports = ProductOptValue = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('ProductOptValue') .define({

    __static__field__number__edit__delete__add__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__ProductOptionId:
        'ProductOptionId',

    __static__field__string__edit__delete__add__read__Label:
        'Label',

    __static__field__string__edit__delete__add__read__Sku:
        'Sku',

    __static__field__number__edit__delete__add__read__IsDefault:
        'IsDefault',

    __static__field__string__edit__delete__add__read__Name:
        'Name',

    __static__field__number__edit__delete__add__read__OptionIndex:
        'OptionIndex',

    __static__field__number__edit__delete__add__read__PriceAdjustment:
        'PriceAdjustment'

});