module.exports = Product = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds your one-time products (non subscriptions).
.class('Product') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__ProductName:
        'ProductName',

    __static__field__number__edit__add__read__ProductPrice:
        'ProductPrice',

    __static__field__string__edit__add__read__Sku:
        'Sku',

    __static__field__string__edit__add__read__ShortDescription:
        'ShortDescription',

    __static__field__number__edit__add__read__Taxable:
        'Taxable',

    __static__field__number__edit__add__read__CountryTaxable:
        'CountryTaxable',

    __static__field__number__edit__add__read__StateTaxable:
        'StateTaxable',

    __static__field__number__edit__add__read__CityTaxable:
        'CityTaxable',

    __static__field__number__edit__add__read__Weight:
        'Weight',

    __static__field__number__edit__add__read__IsPackage:
        'IsPackage',

    __static__field__number__edit__add__read__NeedsDigitalDelivery:
        'NeedsDigitalDelivery',

    __static__field__string__edit__add__read__Description:
        'Description',

    __static__field__number__edit__add__read__HideInStore:
        'HideInStore',

    __static__field__number__edit__add__read__Status:
        'Status',

    __static__field__string__edit__add__read__TopHTML:
        'TopHTML',

    __static__field__string__edit__add__read__BottomHTML:
        'BottomHTML',

    __static__field__string__edit__add__read__ShippingTime:
        'ShippingTime',

    __static__field__blob__edit__add__read__LargeImage:
        'LargeImage',

    __static__field__string__edit__add__read__InventoryNotifiee:
        'InventoryNotifiee',

    __static__field__number__edit__add__read__InventoryLimit:
        'InventoryLimit',

    __static__field__number__edit__add__read__Shippable:
        'Shippable'

});