var Table = require('../Table');

module.exports = ProductOptValue = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ProductOptValue') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProductOptionId: undefined,

    __field__Label: undefined,

    __field__Sku: undefined,

    __field__IsDefault: undefined,

    __field__Name: undefined,

    __field__OptionIndex: undefined,

    __field__PriceAdjustment: undefined

});