module.exports = ProductOption = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

.class('ProductOption') .define({

    __static__field__primary__number__edit__delete__add__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__ProductId:
        'ProductId',

    __static__field__string__edit__delete__add__read__Label:
        'Label',

    __static__field__number__edit__delete__add__read__IsRequired:
        'IsRequired',

    __static__field__number__edit__delete__add__read__Order:
        'Order',

    __static__field__string__edit__delete__add__read__Name:
        'Name',

    __static__field__number__edit__delete__add__read__MaxChars:
        'MaxChars',

    __static__field__number__edit__delete__add__read__CanEndWith:
        'CanEndWith',

    __static__field__number__edit__delete__add__read__MinChars:
        'MinChars',

    __static__field__number__edit__delete__add__read__AllowSpaces:
        'AllowSpaces',

    __static__field__number__edit__delete__add__read__TextMessage:
        'TextMessage',

    __static__field__enum__edit__delete__add__read__OptionType:
        'OptionType',

    __static__field__string__edit__delete__add__read__CanContain:
        'CanContain',

    __static__field__string__edit__delete__add__read__CanStartWith:
        'CanStartWith'

});