var Table = require('../Table');

module.exports = Product = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Product') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProductName: undefined,

    __field__ProductPrice: undefined,

    __field__Sku: undefined,

    __field__ShortDescription: undefined,

    __field__Taxable: undefined,

    __field__CountryTaxable: undefined,

    __field__StateTaxable: undefined,

    __field__CityTaxable: undefined,

    __field__Weight: undefined,

    __field__IsPackage: undefined,

    __field__NeedsDigitalDelivery: undefined,

    __field__Description: undefined,

    __field__HideInStore: undefined,

    __field__Status: undefined,

    __field__TopHTML: undefined,

    __field__BottomHTML: undefined,

    __field__ShippingTime: undefined,

    __field__LargeImage: undefined,

    __field__InventoryNotifiee: undefined,

    __field__InventoryLimit: undefined,

    __field__Shippable: undefined

});