var Table = require('../Table');

module.exports = ProductCategoryAssign = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ProductCategoryAssign') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProductId: undefined,

    __field__ProductCategoryId: undefined

});