module.exports = ProductCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('ProductCategory') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__string__edit__delete__add__read__CategoryDisplayName:
        'CategoryDisplayName',

    __static__field__blob__edit__delete__add__read__CategoryImage:
        'CategoryImage',

    __static__field__number__edit__delete__add__read__CategoryOrder:
        'CategoryOrder',

    __static__field__number__edit__delete__add__read__ParentId:
        'ParentId'

});