var Table = require('../Table');

module.exports = ProductCategory = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('ProductCategory') .extends(Table) .define({

    __field__Id: undefined,

    __field__CategoryDisplayName: undefined,

    __field__CategoryImage: undefined,

    __field__CategoryOrder: undefined,

    __field__ParentId: undefined

});