module.exports = ProductCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This holds your products' categories and subcategories
.class('ProductCategory') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__delete__add__read__CategoryDisplayName:
        'CategoryDisplayName',

    __static__field__blob__edit__delete__add__read__CategoryImage:
        'CategoryImage',

    __static__field__number__edit__delete__add__read__CategoryOrder:
        'CategoryOrder',

    __static__field__number__edit__delete__add__read__ParentId:
        'ParentId'

});