module.exports = RecurringOrder = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// This table holds all the subscriptions generated on contacts. For each contact
// that has a subscription you will find a row in this table.
.class('RecurringOrder') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__ContactId:
        'ContactId',

    __static__field__number__read__OriginatingOrderId:
        'OriginatingOrderId',

    __static__field__number__edit__add__read__ProgramId:
        'ProgramId',

    __static__field__number__edit__add__read__SubscriptionPlanId:
        'SubscriptionPlanId',

    __static__field__number__edit__add__read__ProductId:
        'ProductId',

    __static__field__datetime__edit__add__read__StartDate:
        'StartDate',

    __static__field__datetime__edit__add__read__EndDate:
        'EndDate',

    __static__field__datetime__edit__add__read__LastBillDate:
        'LastBillDate',

    __static__field__datetime__read__NextBillDate:
        'NextBillDate',

    __static__field__datetime__edit__add__read__PaidThruDate:
        'PaidThruDate',

    __static__field__string__edit__add__read__BillingCycle:
        'BillingCycle',

    __static__field__number__edit__add__read__Frequency:
        'Frequency',

    __static__field__number__edit__add__read__BillingAmt:
        'BillingAmt',

    __static__field__string__edit__add__read__Status:
        'Status',

    __static__field__string__edit__add__read__ReasonStopped:
        'ReasonStopped',

    __static__field__number__edit__add__read__AutoCharge:
        'AutoCharge',

    __static__field__number__edit__add__read__CC1:
        'CC1',

    __static__field__number__edit__add__read__CC2:
        'CC2',

    __static__field__number__edit__add__read__NumDaysBetweenRetry:
        'NumDaysBetweenRetry',

    __static__field__number__edit__add__read__MaxRetry:
        'MaxRetry',

    __static__field__number__edit__add__read__MerchantAccountId:
        'MerchantAccountId',

    __static__field__number__edit__add__read__AffiliateId:
        'AffiliateId',

    __static__field__string__edit__add__read__PromoCode:
        'PromoCode',

    __static__field__number__edit__add__read__LeadAffiliateId:
        'LeadAffiliateId',

    __static__field__number__edit__add__read__Qty:
        'Qty',

    __static__field__number__edit__add__read__ShippingOptionId:
        'ShippingOptionId'

});