var Table = require('../Table');

module.exports = RecurringOrderWithContact = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('RecurringOrderWithContact') .extends(Table) .define({

    __field__RecurringOrderId: undefined,

    __field__ContactId: undefined,

    __field__ProgramId: undefined,

    __field__SubscriptionPlanId: undefined,

    __field__ProductId: undefined,

    __field__StartDate: undefined,

    __field__EndDate: undefined,

    __field__LastBillDate: undefined,

    __field__NextBillDate: undefined,

    __field__PaidThruDate: undefined,

    __field__BillingCycle: undefined,

    __field__Frequency: undefined,

    __field__BillingAmt: undefined,

    __field__Status: undefined,

    __field__ReasonStopped: undefined,

    __field__AutoCharge: undefined,

    __field__CC1: undefined,

    __field__CC2: undefined,

    __field__NumDaysBetweenRetry: undefined,

    __field__MaxRetry: undefined,

    __field__MerchantAccountId: undefined,

    __field__AffiliateId: undefined,

    __field__PromoCode: undefined,

    __field__LeadAffiliateId: undefined,

    __field__Qty: undefined,

    __field__City: undefined,

    __field__Email: undefined,

    __field__EmailAddress2: undefined,

    __field__EmailAddress3: undefined,

    __field__FirstName: undefined,

    __field__HTMLSignature: undefined,

    __field__ContactId: undefined,

    __field__LastName: undefined,

    __field__MiddleName: undefined,

    __field__Nickname: undefined,

    __field__Phone1: undefined,

    __field__Phone1Ext: undefined,

    __field__Phone1Type: undefined,

    __field__Phone2: undefined,

    __field__Phone2Ext: undefined,

    __field__Phone2Type: undefined,

    __field__PostalCode: undefined,

    __field__Signature: undefined,

    __field__SpouseName: undefined,

    __field__State: undefined,

    __field__Country: undefined,

    __field__StreetAddress1: undefined,

    __field__StreetAddress2: undefined,

    __field__Suffix: undefined,

    __field__Title: undefined,

    __field__ZipFour1: undefined

});