var Table = require('../Table');

module.exports = RecurringOrder = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('RecurringOrder') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__OriginatingOrderId: undefined,

    __field__ProgramId: undefined,

    __field__SubscriptionPlanId: undefined,

    __field__ProductId: undefined,

    __field__StartDate: undefined,

    __field__EndDate: undefined,

    __field__LastBillDate: undefined,

    __field__NextBillDate: undefined,

    __field__PaidThruDate: undefined,

    __field__BillingCycle: undefined,

    __field__Frequency: undefined,

    __field__BillingAmt: undefined,

    __field__Status: undefined,

    __field__ReasonStopped: undefined,

    __field__AutoCharge: undefined,

    __field__CC1: undefined,

    __field__CC2: undefined,

    __field__NumDaysBetweenRetry: undefined,

    __field__MaxRetry: undefined,

    __field__MerchantAccountId: undefined,

    __field__AffiliateId: undefined,

    __field__PromoCode: undefined,

    __field__LeadAffiliateId: undefined,

    __field__Qty: undefined,

    __field__ShippingOptionId: undefined

});