var Table = require('../Table');

module.exports = Referral = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Referral') .extends(Table) .define({

    __field__Id: undefined,

    __field__ContactId: undefined,

    __field__AffiliateId: undefined,

    __field__DateSet: undefined,

    __field__DateExpires: undefined,

    __field__IPAddress: undefined,

    __field__Source: undefined,

    __field__Info: undefined,

    __field__Type: undefined

});