module.exports = SavedFilter = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// This table holds all saved searches and saved reports created by users within
// Infusionsoft.
.class('SavedFilter') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__read__FilterName:
        'FilterName',

    __static__field__string__read__ReportStoredName:
        'ReportStoredName',

    __static__field__number__read__UserId:
        'UserId'

});