var Table = require('../Table');

module.exports = SavedFilter = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('SavedFilter') .extends(Table) .define({

    __field__Id: undefined,

    __field__FilterName: undefined,

    __field__ReportStoredName: undefined,

    __field__UserId: undefined

});