var Table = require('../Table');

module.exports = StageMove = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('StageMove') .extends(Table) .define({

    __field__Id: undefined,

    __field__OpportunityId: undefined,

    __field__MoveDate: undefined,

    __field__MoveToStage: undefined,

    __field__MoveFromStage: undefined,

    __field__PrevStageMoveDate: undefined,

    __field__CreatedBy: undefined,

    __field__DateCreated: undefined,

    __field__UserId: undefined

});