var Table = require('../Table');

module.exports = SubscriptionPlan = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('SubscriptionPlan') .extends(Table) .define({

    __field__Id: undefined,

    __field__ProductId: undefined,

    __field__Cycle: undefined,

    __field__Frequency: undefined,

    __field__PreAuthorizeAmount: undefined,

    __field__Prorate: undefined,

    __field__Active: undefined,

    __field__PlanPrice: undefined

});