module.exports = SubscriptionPlan = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

.class('SubscriptionPlan') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__add__read__ProductId:
        'ProductId',

    __static__field__string__edit__add__read__Cycle:
        'Cycle',

    __static__field__number__edit__add__read__Frequency:
        'Frequency',

    __static__field__number__edit__add__read__PreAuthorizeAmount:
        'PreAuthorizeAmount',

    __static__field__boolean__edit__add__read__Prorate:
        'Prorate',

    __static__field__boolean__edit__add__read__Active:
        'Active',

    __static__field__number__edit__add__read__PlanPrice:
        'PlanPrice'

});