var Table = require('../Table');

module.exports = Template = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Template') .extends(Table) .define({

    __field__Id: undefined,

    __field__PieceType: undefined,

    __field__PieceTitle: undefined,

    __field__Categories: undefined

});