var Table = require('../Table');

module.exports = Ticket = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('Ticket') .extends(Table) .define({

    __field__Id: undefined,

    __field__IssueId: undefined,

    __field__ContactId: undefined,

    __field__UserId: undefined,

    __field__DevId: undefined,

    __field__TicketTitle: undefined,

    __field__TicketApplication: undefined,

    __field__TicketCategory: undefined,

    __field__TicketTypeId: undefined,

    __field__Summary: undefined,

    __field__Stage: undefined,

    __field__Priority: undefined,

    __field__Ordering: undefined,

    __field__DateCreated: undefined,

    __field__CreatedBy: undefined,

    __field__LastUpdated: undefined,

    __field__LastUpdatedBy: undefined,

    __field__CloseDate: undefined,

    __field__FolowUpDate: undefined,

    __field__TargetCompletionDate: undefined,

    __field__DateInStage: undefined,

    __field__TimeSpent: undefined,

    __field__HasCustomerCalled: undefined

});