module.exports = TicketStage = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// DEPRECATED - This table holds the ticket stages. This is part of a ticketing
// module Infusionsoft no longer offers.
.class('TicketStage') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__read__StageName:
        'StageName'

});