module.exports = Ticket = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:00 GMT-0500 (CDT)

// DEPRECATED - This table holds data about service tickets. This is part of a
// ticketing module Infusionsoft no longer offers.
.class('Ticket') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__IssueId:
        'IssueId',

    __static__field__number__edit__delete__add__read__ContactId:
        'ContactId',

    __static__field__number__edit__delete__add__read__UserId:
        'UserId',

    __static__field__number__edit__delete__add__read__DevId:
        'DevId',

    __static__field__string__edit__delete__add__read__TicketTitle:
        'TicketTitle',

    __static__field__string__edit__delete__add__read__TicketApplication:
        'TicketApplication',

    __static__field__number__edit__delete__add__read__TicketCategory:
        'TicketCategory',

    __static__field__number__edit__delete__add__read__TicketTypeId:
        'TicketTypeId',

    __static__field__string__edit__delete__add__read__Summary:
        'Summary',

    __static__field__number__edit__delete__add__read__Stage:
        'Stage',

    __static__field__number__edit__delete__add__read__Priority:
        'Priority',

    __static__field__number__edit__delete__add__read__Ordering:
        'Ordering',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__edit__delete__add__read__CreatedBy:
        'CreatedBy',

    __static__field__datetime__read__LastUpdated:
        'LastUpdated',

    __static__field__number__edit__delete__add__read__LastUpdatedBy:
        'LastUpdatedBy',

    __static__field__datetime__edit__delete__add__read__CloseDate:
        'CloseDate',

    __static__field__datetime__edit__delete__add__read__FolowUpDate:
        'FolowUpDate',

    __static__field__datetime__edit__delete__add__read__TargetCompletionDate:
        'TargetCompletionDate',

    __static__field__datetime__edit__delete__add__read__DateInStage:
        'DateInStage',

    __static__field__number__edit__delete__add__read__TimeSpent:
        'TimeSpent',

    __static__field__number__edit__delete__add__read__HasCustomerCalled:
        'HasCustomerCalled'

});