module.exports = TicketType = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// DEPRECATED - This table holds data related to the ticketing module Infusionsoft
// no longer offers.
.class('TicketType') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__CategoryId:
        'CategoryId',

    __static__field__string__read__Label:
        'Label'

});