module.exports = User = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 00:43:56 GMT-0500 (CDT)

.class('User') .define({

    __static__field__string__read__City:
        'City',

    __static__field__string__read__Email:
        'Email',

    __static__field__string__read__EmailAddress2:
        'EmailAddress2',

    __static__field__string__read__EmailAddress3:
        'EmailAddress3',

    __static__field__string__read__FirstName:
        'FirstName',

    __static__field__string__read__HTMLSignature:
        'HTMLSignature',

    __static__field__number__read__Id:
        'Id',

    __static__field__string__read__LastName:
        'LastName',

    __static__field__string__read__MiddleName:
        'MiddleName',

    __static__field__string__read__Nickname:
        'Nickname',

    __static__field__string__read__Phone1:
        'Phone1',

    __static__field__string__read__Phone1Ext:
        'Phone1Ext',

    __static__field__string__read__Phone1Type:
        'Phone1Type',

    __static__field__string__read__Phone2:
        'Phone2',

    __static__field__string__read__Phone2Ext:
        'Phone2Ext',

    __static__field__string__read__Phone2Type:
        'Phone2Type',

    __static__field__string__read__PostalCode:
        'PostalCode',

    __static__field__string__read__Signature:
        'Signature',

    __static__field__string__read__SpouseName:
        'SpouseName',

    __static__field__string__read__State:
        'State',

    __static__field__string__read__StreetAddress1:
        'StreetAddress1',

    __static__field__string__read__StreetAddress2:
        'StreetAddress2',

    __static__field__string__read__Suffix:
        'Suffix',

    __static__field__string__read__Title:
        'Title',

    __static__field__string__read__ZipFour1:
        'ZipFour1'

});