var Table = require('../Table');

module.exports = User = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('User') .extends(Table) .define({

    __field__City: undefined,

    __field__Email: undefined,

    __field__EmailAddress2: undefined,

    __field__EmailAddress3: undefined,

    __field__FirstName: undefined,

    __field__HTMLSignature: undefined,

    __field__Id: undefined,

    __field__LastName: undefined,

    __field__MiddleName: undefined,

    __field__Nickname: undefined,

    __field__Phone1: undefined,

    __field__Phone1Ext: undefined,

    __field__Phone1Type: undefined,

    __field__Phone2: undefined,

    __field__Phone2Ext: undefined,

    __field__Phone2Type: undefined,

    __field__PostalCode: undefined,

    __field__Signature: undefined,

    __field__SpouseName: undefined,

    __field__State: undefined,

    __field__StreetAddress1: undefined,

    __field__StreetAddress2: undefined,

    __field__Suffix: undefined,

    __field__Title: undefined,

    __field__ZipFour1: undefined

});