var Table = require('../Table');

module.exports = UserGroup = require('typedef')

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.class('UserGroup') .extends(Table) .define({

    __field__Id: undefined,

    __field__Name: undefined,

    __field__OwnerId: undefined

});