module.exports = UserGroup = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Fri Aug 09 2013 13:46:55 GMT-0500 (CDT)

// This table holds user group information. These are groupings for your system
// users, not contacts.
.class('UserGroup') .define({

    __static__field__number__read__Id:
        'Id',

    __static__field__string__read__Name:
        'Name',

    __static__field__number__read__OwnerId:
        'OwnerId'

});