var IService = require('../IService');

module.exports = IAffiliateService = require('typedef')

// APIAffiliateService is used to pull commission data and activities for
// affiliates. With this service, you have access to Clawbacks, Commissions,
// Payouts, Running Totals, and the Activity Summary. The methods in the
// APIAffiliateService mirror the reports produced inside Infusionsoft. To
// manage affiliate information (ie Name, Phone, etc.) you will need to use
// the DataService.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IAffiliateService') .implements(IService) .define({

    // The affClawbacks method is used when you need to retrieve all clawed
    // back commissions for a particular affiliate. Claw backs typically occur
    // when an order has been refunded to the customer
    __xmlrpc__affClawbacks: function(affiliateId, filterStartDate,
        filterEndDate) {},

    // This method is used to retrieve all commissions for a specific
    // affiliate within a date range
    __xmlrpc__affCommissions: function(affiliateId, filterStartDate,
        filterEndDate) {},

    // Gets a list of the Redirect Links for the specified Affiliate.
    __xmlrpc__getRedirectLinksForAffiliate: function(affiliateId) {},

    // This method is used to retrieve all payments for a specific affiliate
    // within a date range
    __xmlrpc__affPayouts: function(affiliateId, filterStartDate,
        filterEndDate) {},

    // The affRunningTotals method is used to retrieve the current balances
    // for Amount Earned, Clawbacks, and Running Balance.
    __xmlrpc__affRunningTotals: function(affiliateIds) {},

    // The affSummary method is used to retrieve a summary of statistics for a
    // list of affiliates
    __xmlrpc__affSummary: function(affiliateId, filterStartDate,
        filterEndDate) {}

});