module.exports = IAffiliateService = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:03 GMT-0500 (CDT)

// APIAffiliateService is used to pull commission data and activities for
// affiliates. With this service, you have access to Clawbacks, Commissions,
// Payouts, Running Totals, and the Activity Summary. The methods in the
// APIAffiliateService mirror the reports produced inside Infusionsoft. To manage
// affiliate information (ie Name, Phone, etc.) you will need to use the
// DataService.
.interface('IAffiliateService') .define({

    // The affClawbacks method is used when you need to retrieve all clawed back
    // commissions for a particular affiliate. Claw backs typically occur when an
    // order has been refunded to the customer
    __xmlrpc__affClawbacks: function(apiKey, affiliateId, filterStartDate,
        filterEndDate) {},

    // This method is used to retrieve all commissions for a specific affiliate
    // within a date range
    __xmlrpc__affCommissions: function(apiKey, affiliateId,
        filterStartDate, filterEndDate) {},

    // Gets a list of the Redirect Links for the specified Affiliate.
    __xmlrpc__getRedirectLinksForAffiliate: function(apiKey, affiliateId) {},

    // This method is used to retrieve all payments for a specific affiliate
    // within a date range
    __xmlrpc__affPayouts: function(apiKey, affiliateId, filterStartDate,
        filterEndDate) {},

    // The affRunningTotals method is used to retrieve the current balances for
    // Amount Earned, Clawbacks, and Running Balance.
    __xmlrpc__affRunningTotals: function(apiKey, affiliateIds) {},

    // The affSummary method is used to retrieve a summary of statistics for a
    // list of affiliates
    __xmlrpc__affSummary: function(apiKey, affiliateId, filterStartDate,
        filterEndDate) {}

});