var IService = require('../IService');

module.exports = IDataService = require('typedef')

// The DataService is used to manipulate most data in Infusionsoft. It permits
// you to work on any available tables and has a wide range of uses. Here's a
// list of all available tables, and the fields they contain: InfusionSoft
// Tables (Pro Tip: Open this in a new tab.)

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IDataService') .implements(IService) .define({

    // Adds a record to the specified table in Infusionsoft.
    __xmlrpc__add: function(table, values) {},

    // Loads a struct with data from the given database record
    __xmlrpc__load: function(table, recordId, wantedFields) {},

    // Updates the specified record (indicated by ID) with the data provided
    __xmlrpc__update: function(table, Id, values) {},

    // Deletes the specified record in the given table from the database
    __xmlrpc__delete: function(table, Id) {},

    // This will locate all records in a given table that match the criteria
    // for a given field
    __xmlrpc__findByField: function(table, limit, page, fieldName,
        fieldValue, returnFields) {},

    // Performs a query across the given table based on the query data
    __xmlrpc__query: function(table, limit, page, queryData, selectedFields) {},

    // Creates a new custom fields within Infusionsoft
    __xmlrpc__addCustomField: function(customFieldType, displayName,
        dataType, headerId) {},

    // This method is used to authenticate an Infusionsoft username and
    // password(md5 hash). If the credentials match it will return back a User
    // ID, if the credentials do not match it will send back an error message
    __xmlrpc__authenticateUser: function(username, passwordHash) {},

    // This method will return back the data currently configured in a user
    // configured application setting
    __xmlrpc__getAppSetting: function(module, setting) {},

    // Returns an iCalendar entry for the given appointment
    __xmlrpc__getAppointmentCal: function(appointmentId) {},

    // Returns a temporary API key which is valid for one hour if given a
    // valid Vendor key and user credentials. For security, never store a
    // users password in plaintext. You only need to pass the MD5 hash with
    // this method, so only the MD5 hash needs to be stored.
    __xmlrpc__getTemporaryKey: function(vendorKey, username, passwordHash) {},

    // Updates a custom field. Every field can have it's display name and
    // group id changed, but only certain data types will allow you to change
    // values(dropdown, listbox, radio, etc)
    __xmlrpc__updateCustomField: function(customFieldId, values) {}

});