module.exports = IDiscountService = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:03 GMT-0500 (CDT)

// DiscountService is used to manage products. You can add, update and find
// products in addition to managing follow up sequences, tags and action sets.
.interface('IDiscountService') .define({

    // Adds a Free trial
    __xmlrpc__addFreeTrial: function(apiKey, name, description,
        freeTrialDays, hidePrice, subscriptionPlanId) {},

    // Returns the options and values of the free trial id passed
    __xmlrpc__getFreeTrial: function(apiKey, trialId) {},

    // Adds a order total discount
    __xmlrpc__addOrderTotalDiscount: function(apiKey, name, description,
        applyDiscountToCommission, percentOrAmt, amt, payType) {},

    // Adds a order total discount
    __xmlrpc__getOrderTotalDiscount: function(apiKey, id) {},

    // Adds a category discount
    __xmlrpc__addCategoryDiscount: function(apiKey, name, description,
        applyDiscountToCommission, amt) {},

    // Returns the options and values of the category discount id passed
    __xmlrpc__getCategoryDiscount: function(apiKey, id) {},

    // Assigns a product to a category discount
    __xmlrpc__addCategoryAssignmentToCategoryDiscount: function(apiKey, id,
        productId) {},

    // Returns the options and values of the category assignment for category
    // discount passed
    __xmlrpc__getCategoryAssignmentsForCategoryDiscount: function(apiKey,
        id) {},

    // Add a product total discount
    __xmlrpc__addProductTotalDiscount: function(apiKey, name, description,
        applyDiscountToCommission, productId, percentOrAmt, amt) {},

    // Returns the options and values of the product total discount id passed
    __xmlrpc__getProductTotalDiscount: function(apiKey, id) {},

    // Adds a shipping total discount
    __xmlrpc__addShippingTotalDiscount: function(apiKey, name, description,
        applyDiscountToCommission, percentOrAmt, amt) {},

    // Returns the options and values of the shipping total discount id passed
    __xmlrpc__getShippingTotalDiscount: function(apiKey, id) {}

});