module.exports = IFileService = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Wed Jan 08 2014 12:43:55 GMT-0600 (CST)

// The FileService methods allow you to create and modify files inside the
// Infusionsoft System.
.interface('IFileService') .define({

    // This method retrieves the file data for the given ID number.
    __xmlrpc__getFile: function(apiKey, FileId) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__getDownloadUrl: function(apiKey, FileId) {},

    // This method uploads the file to Infusionsoft. The optional contactId
    // parameter is used to place the file in a specific contact's filebox.
    __xmlrpc__uploadFile: function(apiKey, FileName, Base64EncodedData,
        _ContactId) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__replaceFile: function(apiKey, FileId, Base64EncodedData) {},

    // This method will return a string of the download URL for the given file.
    __xmlrpc__renameFile: function(apiKey, FileId, fileName) {}

});