var IService = require('../IService');

module.exports = IFunnelService = require('typedef')

// Funnel Service is used to add contacts to your sequences

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IFunnelService') .implements(IService) .define({

    // Returns the result of a goal being achieved.
    __xmlrpc__achieveGoal: function(Integration, Call Name, contactId) {}

});