module.exports = IProductService = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:03 GMT-0500 (CDT)

// ProductService is used to manage products. You can add, update and find
// products in addition to managing follow up sequences, tags and action sets.
.interface('IProductService') .define({

    // Returns a product inventory provided the Id
    __xmlrpc__getInventory: function(apiKey, productId) {},

    // Increments the inventory by one product, provided you pass the productId to
    // increment withy
    __xmlrpc__incrementInventory: function(apiKey, productId) {},

    // Decrements the inventory by one product, provided you pass the productId to
    // decrement with
    __xmlrpc__decrementInventory: function(apiKey, productId) {},

    // Increases the inventory with a particular product by the quantity you
    // specify
    __xmlrpc__increaseInventory: function(apiKey, productId, quantity) {},

    // Decreases the inventory with a particular product by the quantity you
    // specify
    __xmlrpc__decreaseInventory: function(apiKey, productId, quantity) {},

    // Deactivates the specified Credit Card
    __xmlrpc__deactivateCreditCard: function(apiKey, creditCardId) {}

});