var IService = require('../IService');

module.exports = IShippingService = require('typedef')

// ShippingService is used to manage products. You can add, update and find
// products in addition to managing follow up sequences, tags and action sets.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IShippingService') .implements(IService) .define({

    // Returns all shipping options configured
    __xmlrpc__getAllShippingOptions: function() {},

    // Returns the options and values of the flat rate shipping option provided
    __xmlrpc__getFlatRateShippingOption: function(optionId) {},

    // Returns the options and values of the order total shipping option
    // provided
    __xmlrpc__getOrderTotalShippingOption: function(optionId) {},

    // Returns the options and values of the order total shipping ranges
    // option provided
    __xmlrpc__getOrderTotalShippingRanges: function(optionId) {},

    // Returns the options and values of the product based shipping option
    // provided
    __xmlrpc__getProductBasedShippingOption: function(optionId) {},

    // Returns the options and values of the order quantity shipping option
    // provided
    __xmlrpc__getOrderQuantityShippingOption: function(optionId) {},

    // Returns the options and values of the weight based shipping option
    // provided
    __xmlrpc__getWeightBasedShippingOption: function(optionId) {},

    // Returns the options and values of the ups shipping option provided
    __xmlrpc__getUpsShippingOption: function(optionId) {}

});