var IService = require('../IService');

module.exports = IWebFormService = require('typedef')

// The WebFormService is used to work with web forms within Infusionsoft.

// THIS CODE WAS GENERATED BY A TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/infusionsoft-api

.interface('IWebFormService') .implements(IService) .define({

    // This retrieves the web form names and Id numbers from the application.
    __xmlrpc__getMap: function() {},

    // This retrieves the HTML for the given web form
    __xmlrpc__getHTML: function(webFormId) {}

});