module.exports = IWebFormService = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Mon Aug 19 2013 21:29:03 GMT-0500 (CDT)

// The WebFormService is used to work with web forms within Infusionsoft.
.interface('IWebFormService') .define({

    // This retrieves the web form names and Id numbers from the application.
    __xmlrpc__getMap: function(apiKey) {},

    // This retrieves the HTML for the given web form
    __xmlrpc__getHTML: function(apiKey, webFormId) {}

});